version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: accident_detection_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: accident_detection
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./accident_detection.sql:/docker-entrypoint-initdb.d/accident_detection.sql
    networks:
      - app-network

  # Flask Backend Application
  backend:
    build: .
    container_name: accident_detection_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
      - DB_DATABASE=accident_detection
      - DB_PORT=3306
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
    volumes:
      - ./videos:/app/videos
      - ./processed_videos:/app/processed_videos
      - ./stream_frames:/app/stream_frames
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./accident_clips:/app/accident_clips
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge 